### PR TITLE
Add detector for java object deserialization

### PR DESCRIPTION
**Pull request by minlex**

### CODE REVIEW

**Comment by h3xstream** [comment]
The timing for this new detector is perfect.
Excellent contribution. Clear code, complete description and tested!
A++

**Comment by h3xstream** [comment]
Hi,
I am about to do a release including this new detector.

I don't see why the subclass of ObjectInput is a requirement : https://github.com/minlex/find-sec-bugs/commit/a351750e2bb079385d06a4e8209771afed23f4bf#diff-9ae0464597775b233fd0bf43eea0857aR49

Maybe, I did not understand the vulnerability enough. But I am expecting that any readObject will be vulnerable. Here is an example : https://github.com/jenkinsci/remoting/blob/383a19ee36420a70aa5330a25d7209f80890303a/src/main/java/hudson/remoting/Command.java#L92

**Comment by h3xstream** [comment]
I have change the detector with a less elegant way to detect potential subclass.
One test case for subclass of `ObjectInputStream` was created.

Reason: `JavaClass javaClass = Repository.lookupClass(classConstantOperand);` was trown ClassNotFoundException when the class was not load in the classpath of FindBugs.

Ref: List of subclass of ObjectInputStream in Java 8:
```java
MarshalInputStream (sun.rmi.server)
Applet2ObjectInputStream in AWTAppletAdapter (com.sun.deploy.uitoolkit.impl.awt)
AppletObjectInputStream (sun.plugin)
ClassLoaderObjectInputStream (sun.awt.datatransfer)
DummyStream in GCJInstantiatorBase (org.objenesis.instantiator.gcj)
InputStreamHook (com.sun.corba.se.impl.io)
extObjectInputStream (javax.crypto)
AppletObjectInputStream (sun.applet)
ObjectInputStreamWithLoader (java.beans)
MLetObjectInputStream (javax.management.loading)
ObjectInputStreamWithLoader in RMIConnector (javax.management.remote.rmi)
ObjectInputStreamWithLoader (com.sun.jmx.mbeanserver)
ClassLoaderObjectInputStream (org.apache.commons.io.input)
IndexFileObjectInputStream (com.sun.deploy.cache)
LoaderInputStream in Obj (com.sun.jndi.ldap)
MarshalObjectInputStream in IDLJavaSerializationInputStream (com.sun.corba.se.impl.encoding)
```

**Comment by minlex** [comment]
Ok. I made it so in case of some class extending ObjectInput or ObjectInputStream. But this way probably would be better.

**Pull request merged**
