### PR TITLE
Improved hardcoded passwords and key detector

### PR DESCRIPTION
**Pull request by formanek**
New version of the detector with higher accuracy. The most important change is that constant values are tracked to a given argument of password or key sink method using flow analysis instead of only guessing the link between constant and method. Heuristics is used to catch positives with too complicated flow, but in contrast to previous detector, fields with suspicious names are reported all for a class in one report and only if they were not reported by high-confidence analysis. More information such as hard coded source is added to the bug report (if available) too. I have also integrated OAuth detector into this one (just by altering configuration).

### CODE REVIEW

**Comment by h3xstream** [comment]
Quick update : The pull request will be integrated soon. I just did not get the time to look at the changes set.

**Comment by formanek** [comment]
I have not created a new branch for taint analysis so commits are here... I have implemented flow analysis, which is tracking "taintness" (taint, uknown, safe or null) at a given code location. Currently, state "taint" is never set (I am going to add it later for explicitly configured taint sources such as reading from file), but constant strings or objects are marked safe. There is a configuration for "transfer methods", where can be specified, how parameters transfer their "taintness" to the return value, to other parameters or to the object invoking the configured method. TaintDetector uses the information from TaintDataFlow to set the priority of the reported bug. All test passed (with some priority changes) and there is some new test code too. I can explain details on request, please try to have a look at the code, I have still many ideas for improvements :)

**Comment by h3xstream** [comment]
I really liked this pull request. It is a long term implementation of taint detection. My previous implementation look very poor compare to this new system.
I also discover many FindBugs API along the code review.

I will remove the artifacts of the wobbly "Replay" mechanism I previously introduce. I will do minor contribution to thing like the list of transfer methods. Other than that, I don't see anything major change to come on my side. I will start to do some testing on large code base to see how it react.

Again.. You did a really great job!

**Comment by h3xstream** [comment]
Mandatory reference to this related issue #14

**Comment by formanek** [comment]
Changes are described in more detail here:
http://www.ysofters.com/2015/08/06/detection-of-hard-coded-passwords-improved/
http://www.ysofters.com/2015/08/31/taint-analysis-added-to-findbugs/

**Pull request merged**
